In [14]:
%pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\huynh\anaconda3\lib\site-packages (1.0.3)
Requirement already satisfied: certifi>=2026.10.19 in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (2026.10.23)
Requirement already satisfied: kagglesdk<1.0,>=0.1.38 in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (0.1.38)
Requirement already satisfied: packaging in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\huynh\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\huynh\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.38->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\huynh\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\huynh\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\huynh\anaconda3\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: colorama in c:\users\huynh\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("dduongdev/shopee-vietnamese-product-reviews-sentiment")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\huynh\.cache\kagglehub\datasets\dduongdev\shopee-vietnamese-product-reviews-sentiment\versions\1

In [16]:
import os
import glob
import pandas as pd

# 1. Tải dataset
path = kagglehub.dataset_download("yoongsin/shopee-sample-data")

# 2. Tự động tìm tất cả file .csv nằm trong thư mục vừa tải về
csv_files = glob.glob(os.path.join(path, "**", "*.csv"), recursive=True)

# 3. Đọc file CSV đầu tiên tìm được
df = pd.read_csv(csv_files[0])

# 4. (Tùy chọn) Lưu ra 1 bản copy tên 'shopee_data.csv' ngay thư mục hiện tại để dùng cho lần sau
df.to_csv(
    r"D:\L-NMPTDL&AI\Stage 1 + 2\DA-AI_Nhom8\DHHTTT20B_TCTA_Nhom8_Stage1\data\shopee_data.csv",
    index=False,
    encoding="utf-8-sig"
)

# 5. Xem 5 dòng đầu
df.head()

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.80,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.90,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...
1,1.41,NaN,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,https://shopee.com.my/Stat-Chinese-Traditional...,5.0,stationery.my,5322309be3b6d9c01d15fa19f5b7ad9a,0.75,shopee,472d22f58af3bb35cf28c6eed7088dc5,17,472d22f58af3bb35cf28c6eed7088dc5,17,https://down-my.img.susercontent.com/file/4147...,Favorite (19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...
2,8.50,"KL City, Kuala Lumpur",Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,https://shopee.com.my/N09-READY-STOCK-MYFOOYIN...,4.9,fooyin88,7a36765d1e2ca2b6a5414ddfeedfefc3,8.50,shopee,ec6ce64f4b77efb38b6392818959f181,8.1k,ec6ce64f4b77efb38b6392818959f181,8.1k,https://down-my.img.susercontent.com/file/23da...,Favorite (21.5k,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...
3,8.70,NaN,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,https://shopee.com.my/%F0%9F%94%A5Shocking-Sal...,4.9,vivi2002,7fc4ab69722e4f788f217b4c044f83eb,8.70,shopee,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,https://down-my.img.susercontent.com/file/df47...,Favorite (3.4k,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...
4,3999.00,"KL City, Kuala Lumpur",Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,https://shopee.com.my/Canon-EOS-70D-18-55mm-IS...,5.0,xpro.gadget,55608f901f4c5384f884de18227d4298,2739.00,shopee,568c2029fed7d22973ff96d0404a8ff8,10,568c2029fed7d22973ff96d0404a8ff8,10,https://down-my.img.susercontent.com/file/4d3a...,Favorite (132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...

In [17]:
df.shape

(20312, 20)

In [18]:
df.columns

Index(['price_ori', 'delivery', 'item_category_detail', 'specification',
       'title', 'w_date', 'link_ori', 'item_rating', 'seller_name',
       'idElastic', 'price_actual', 'sitename', 'idHash', 'total_rating', 'id',
       'total_sold', 'pict_link', 'favorite', 'timestamp', 'desc'],
      dtype='object')

In [19]:
df.head(1)

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.8,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.9,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...

In [20]:
print(df.dtypes)

price_ori               float64
delivery                 object
item_category_detail     object
specification            object
title                    object
w_date                   object
link_ori                 object
item_rating              object
seller_name              object
idElastic                object
price_actual            float64
sitename                 object
idHash                   object
total_rating             object
id                       object
total_sold               object
pict_link                object
favorite                 object
timestamp                 int64
desc                     object
dtype: object